### ISSUE TITLE
Any plans on supporting aarch64?

### ISSUE THREAD

**Issue by mkmkme** [lemire/fastbase64#15]
Hi! I'm currently looking at ways to use this library in ClickHouse (https://github.com/ClickHouse/ClickHouse/issues/31643), and my very first step was to build fastbase64 on my machine. I got several errors on v0.1.0, and on master pretty much the only one is
```
In file included from src/fastavxbase64.c:3:
In file included from /opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/include/x86intrin.h:15:
/opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/include/immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
```

I'm trying to build on Apple M1 Max.
Do you have any plans on supporting ARM?

**Comment by lemire** [comment]
If there was a need, we would extend it,  but there is https://github.com/aklomp/base64 which has adopted many of our algorithms, so there does not seem to be a need for us to support this research library beyond its initial purpose.

So the answer is no. Of course, if you have some argument, we could change our minds.

**Comment by mkmkme** [comment]
Thanks for the quick response! I don't think there would be an argument about that. If I have a follow-up to that, I'll reopen the ticket :)
