### ISSUE TITLE
Issue with fast_avx512bw_base64_encode()

### ISSUE THREAD

**Issue by lano1106** [lemire/fastbase64#17]
I try to encode a 64 bytes string.

the output is garbage, yet the return value returns the expected encoded len:

[2024-03-15 18:26:58] INFO KREST/sendPost m_signatureHdr(88):api-sign: R�Rg�%gSoS9G9?ET?'B'2kH2n=�n�
                                                                                                    ��D6pD1@n1M�M�w.��d�s204vye1PczTMWiZTe8YYg==

I have disabled using fast_avx512bw_base64_encode() and have fallback to fast_avx2_base64_encode() with

```
#if defined(__AVX512BW__) && 0
    return fast_avx512bw_base64_encode(dest, src, len);
#elifdef __AVX2__
    return fast_avx2_base64_encode(dest, src, len);
#else
    return chromium_base64_encode(dest, src, len);
#endif
```

fast_avx2_base64_encode() encodes correctly its input...

This result is by compiling and executing the resulting binary on a sapphirerapids CPU. (AWS c7)

**Comment by lemire** [comment]
The simdutf library will support base64 encoding and decoding in a week or so. Do not use `fastbase64`, it is obsolete and won't be maintained. Just wait for a week or so for simdutf to provide well supported base64 encoding and decoding.

**Comment by lemire** [comment]
As of the last release, simdutf has full support for base64 encoding and decoding. If someone is interested in fixing the issue you have encountered, pull requests are welcome... but maintenance efforts will go toward simdutf.

**Comment by lano1106** [comment]
thx a lot... I have done some hacking to remove the call to the virtual function call... maybe exposing the implementations or document how this can be done is a feature that others would like to have
```
/*
 * code from Daniel Lemire fastbase64 library:
 * https://github.com/lemire/fastbase64
 */
#include "chromiumbase64.cpp"
#if defined(__AVX512BW__) && 0
#include "fastavx512bwbase64.cpp"
#elifdef __AVX2__
#include "fastavxbase64.cpp"
#elifdef __SSE4_2__
#include "simdutf.h"
#include "simdutf/westmere.h"
const simdutf::westmere::implementation westmere_singleton{};
#endif

/*
 * base64_encode()
 */
size_t Base::util::base64_encode(char* dest, const char *src, int len) noexcept
{
#if defined(__AVX512BW__) && 0
    return fast_avx512bw_base64_encode(dest, src, len);
#elifdef __AVX2__
    return fast_avx2_base64_encode(dest, src, len);
#elifdef __SSE4_2__
    return westmere_singleton.binary_to_base64(src, len, dest, 0);
#else
    return chromium_base64_encode(dest, src, len);
#endif
}

/*
 * base64_decode()
 */
size_t Base::util::base64_decode(char *out, const char *input,
                                 int len) noexcept
{
#if defined(__AVX512BW__) && 0
    return fast_avx512bw_base64_decode(out, input, len);
#elifdef __AVX2__
    return fast_avx2_base64_decode(out, input, len);
#elifdef __SSE4_2__
    return westmere_singleton.base64_to_binary(input, len, out, 0).count;
#else
    return chromium_base64_decode(out, input, len);
#endif
}
#endif
```
On a westmere platform, simdutf base64 functions works as expected. I will replace AVX512 implementation to make it point on simdutf as well

**Comment by lano1106** [comment]
iow, a compile-time implementation selection that has 0 runtime cost... this could of course, be applicable to every project using your implementation system ie: simdjson

**Comment by lano1106** [comment]
for the records, I have also just tested the AVX 512 simdutf icelake implementation and it works just fine as opposed to the fastbase64 implementation

**Comment by lemire** [comment]
> iow, a compile-time implementation selection that has 0 runtime cost...

If you target AVX-512 or 64-bit ARM, the simdutf library will already provide zero-cost runtime dispatching (by effectively disabling the dispatching). For other targets, you can do it with macros... although we don't necessarily document it (it is for expert users).

There is no need to modify the source code.
